application: reeljs
version: 1
runtime: python
api_version: 1

handlers:
- url: /jquery\.reel\.js
  static_files: reel-min.js
  upload: reel-min\.js

- url: /favicon\.ico
  static_files: icon.png
  upload: icon\.png

- url: /jquery\.reel-bundle\.js
  static_files: reel-bundle.js
  upload: reel-bundle\.js

- url: /jquery\.reel-devel\.js
  static_files: reel.js
  upload: reel\.js

- url: /jquery\.reel-(\d+)\.gif
  static_files: jquery.reel-\1.gif
  upload: jquery\.reel-\d+\.gif

- url: /.*
  script: cacheheaders.py
