runtime: python27
threadsafe: false

api_version: 1

default_expiration: 30d

inbound_services:
- warmup

handlers:
- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
