application: reeljs
version: 1
runtime: python
api_version: 1

default_expiration: 7d

handlers:

# Latest

- url: /jquery\.reel\.js
  static_files: reel-1.1.4-min.js
  upload: reel-1\.1\.4-min\.js

- url: /jquery\.reel-bundle\.js
  static_files: reel-1.1.4-bundle.js
  upload: reel-1\.1\.4-bundle\.js

- url: /jquery\.reel-devel\.js
  static_files: reel-1.1.4.js
  upload: reel-1\.1\.4\.js

- url: /jquery\.reel\.js/embed
  script: embed.jquery.reel-1.1.4.py

# Edge (1.2rc2)

- url: /jquery\.reel-edge.js
  static_files: reel-1.2rc2-min.js
  upload: reel-1\.2rc2-min\.js

- url: /jquery\.reel-edge-bundle\.js
  static_files: reel-1.2rc2-bundle.js
  upload: reel-1\.2rc2-bundle\.js

- url: /jquery\.reel-edge-devel\.js
  static_files: reel-1.2rc2.js
  upload: reel-1\.2rc2\.js

- url: /jquery\.reel-edge\.js/embed
  script: embed.jquery.reel-1.2.py

# 1.1.x

- url: /jquery\.reel-1\.1\.js
  static_files: reel-1.1.4-min.js
  upload: reel-1\.1\.4-min\.js

- url: /jquery\.reel-1\.1-bundle\.js
  static_files: reel-1.1.4-bundle.js
  upload: reel-1\.1\.4-bundle\.js

- url: /jquery\.reel-1\.1-devel\.js
  static_files: reel-1.1.4.js
  upload: reel-1\.1\.4\.js

- url: /jquery\.reel-1\.1\.js/embed
  script: embed.jquery.reel-1.1.4.py

# 1.2.x

- url: /jquery\.reel-1\.2\.js
  static_files: reel-1.2rc2-min.js
  upload: reel-1\.2rc2-min\.js

- url: /jquery\.reel-1\.2-bundle\.js
  static_files: reel-1.2rc2-bundle.js
  upload: reel-1\.2rc2-bundle\.js

- url: /jquery\.reel-1\.2-devel\.js
  static_files: reel-1.2rc2.js
  upload: reel-1\.2rc2.js

- url: /jquery\.reel-1\.2\.js/embed
  script: embed.jquery.reel-1.2.py

# 1.1.4

- url: /jquery\.reel-1\.1\.4\.js
  static_files: reel-1.1.4-min.js
  upload: reel-1\.1\.4-min\.js

- url: /jquery\.reel-1\.1\.4-bundle\.js
  static_files: reel-1.1.4-bundle.js
  upload: reel-1\.1\.4-bundle\.js

- url: /jquery\.reel-1\.1\.4-devel\.js
  static_files: reel-1.1.4.js
  upload: reel-1\.1\.4\.js

- url: /jquery\.reel-1\.1\.4\.js/embed
  script: embed.jquery.reel-1.1.4.py

# 1.1.3

- url: /jquery\.reel-1\.1\.3\.js
  static_files: reel-1.1.3-min.js
  upload: reel-1\.1\.3-min\.js

- url: /jquery\.reel-1\.1\.3-bundle\.js
  static_files: reel-1.1.3-bundle.js
  upload: reel-1\.1\.3-bundle\.js

- url: /jquery\.reel-1\.1\.3-devel\.js
  static_files: reel-1.1.3.js
  upload: reel-1\.1\.3\.js

- url: /jquery\.reel-1\.1\.3\.js/embed
  script: embed.jquery.reel-1.1.3.py

# 1.1.2

- url: /jquery\.reel-1\.1\.2\.js
  static_files: reel-1.1.2-min.js
  upload: reel-1\.1\.2-min\.js

- url: /jquery\.reel-1\.1\.2-bundle\.js
  static_files: reel-1.1.2-bundle.js
  upload: reel-1\.1\.2-bundle\.js

- url: /jquery\.reel-1\.1\.2-devel\.js
  static_files: reel-1.1.2.js
  upload: reel-1\.1\.2\.js

- url: /jquery\.reel-1\.1\.2\.js/embed
  script: embed.jquery.reel-1.1.2.py

# 1.1.1

- url: /jquery\.reel-1\.1\.1\.js
  static_files: reel-1.1.1-min.js
  upload: reel-1\.1\.1-min\.js

- url: /jquery\.reel-1\.1\.1-bundle\.js
  static_files: reel-1.1.1-bundle.js
  upload: reel-1\.1\.1-bundle\.js

- url: /jquery\.reel-1\.1\.1-devel\.js
  static_files: reel-1.1.1.js
  upload: reel-1\.1\.1\.js

- url: /jquery\.reel-1\.1\.1\.js/embed
  script: embed.jquery.reel-1.1.1.py

# 1.1.0

- url: /jquery\.reel-1\.1\.0\.js
  static_files: reel-1.1-min.js
  upload: reel-1\.1-min\.js

- url: /jquery\.reel-1\.1\.0-bundle\.js
  static_files: reel-1.1-bundle.js
  upload: reel-1\.1-bundle\.js

- url: /jquery\.reel-1\.1\.0-devel\.js
  static_files: reel-1.1.js
  upload: reel-1\.1\.js

- url: /jquery\.reel-1\.1\.0\.js/embed
  script: embed.jquery.reel-1.1.0.py

# 1.0.x

- url: /jquery\.reel-1\.0\.js
  static_files: reel-1.0.4-min.js
  upload: reel-1\.0\.4-min\.js

- url: /jquery\.reel-1\.0-bundle\.js
  static_files: reel-1.0.4-bundle.js
  upload: reel-1\.0\.4-bundle\.js

- url: /jquery\.reel-1\.0-devel\.js
  static_files: reel-1.0.4.js
  upload: reel-1\.0\.4\.js

- url: /jquery\.reel-1\.0\.js/embed
  script: embed.jquery.reel-1.0.4.py


# Badges

- url: /jquery\.reel-(\d+)\.gif
  static_files: jquery.reel-\1.gif
  upload: jquery\.reel-\d+\.gif

- url: /favicon\.ico
  static_files: icon.png
  upload: icon\.png


# 1.2 Cursors (CURs)

- url: /jquery\.reel\.cur
  static_files: jquery.reel-white.cur
  upload: jquery\.reel-white\.cur
  mime_type: image/x-icon

- url: /jquery\.reel-white\.cur
  static_files: jquery.reel-white.cur
  upload: jquery\.reel-white\.cur
  mime_type: image/x-icon

- url: /jquery\.reel-black\.cur
  static_files: jquery.reel-white.cur
  upload: jquery\.reel-white\.cur
  mime_type: image/x-icon

- url: /jquery\.reel-drag\.cur
  static_files: jquery.reel-drag.cur
  upload: jquery\.reel-drag\.cur
  mime_type: image/x-icon

- url: /jquery\.reel-drag-down\.cur
  static_files: jquery.reel-drag-down.cur
  upload: jquery\.reel-drag-down\.cur
  mime_type: image/x-icon


# 1.1 Cursors (GIFs)

- url: /jquery\.reel\.cursor-drag\.gif
  static_files: jquery.reel.cursor-drag.gif
  upload: jquery\.reel\.cursor-drag\.gif
  mime_type: image/gif

- url: /jquery\.reel\.cursor-drag-down\.gif
  static_files: jquery.reel.cursor-drag-down.gif
  upload: jquery\.reel\.cursor-drag-down\.gif
  mime_type: image/gif


# Licenses

- url: /MIT-LICENSE\.txt
  static_files: MIT-LICENSE.txt
  upload: MIT-LICENSE\.txt

- url: /GPL-LICENSE\.txt
  static_files: GPL-LICENSE.txt
  upload: GPL-LICENSE\.txt







# Essentials

- url: /blank\.gif
  static_files: blank.gif
  upload: blank\.gif



- url: /.*
  script: cacheheaders.py
