application: reeljs
version: 1
runtime: python
api_version: 1

handlers:
- url: /jquery.reel.js
  static_files: reel-min.js
  upload: reel-min.js

- url: /favicon.ico
  static_files: icon.png
  upload: icon.png

- url: /jquery.reel-bundle.js
  static_files: reel-bundle.js
  upload: reel-bundle.js

- url: /jquery.reel-devel.js
  static_files: reel.js
  upload: reel.js

- url: /jquery.reel.120x30.gif
  static_files: jquery.reel.120x30.gif
  upload: jquery.reel.120x30.gif

- url: /jquery.reel.120x30-green.gif
  static_files: jquery.reel.120x30-green.gif
  upload: jquery.reel.120x30-green.gif

- url: /jquery.reel.120x30-red.gif
  static_files: jquery.reel.120x30-red.gif
  upload: jquery.reel.120x30-red.gif

- url: /jquery.reel.120x30-grey.gif
  static_files: jquery.reel.120x30-grey.gif
  upload: jquery.reel.120x30-grey.gif

- url: /.*
  script: cacheheaders.py
