application: reeljs
version: 1
runtime: python
api_version: 1

handlers:

# Latest

- url: /jquery\.reel\.js
  static_files: reel-1.1.1-min.js
  upload: reel-1\.1\.1-min\.js

- url: /jquery\.reel-bundle\.js
  static_files: reel-1.1.1-bundle.js
  upload: reel-1\.1\.1-bundle\.js

- url: /jquery\.reel-devel\.js
  static_files: reel-1.1.1.js
  upload: reel-1\.1\.1\.js

# 1.1.x

- url: /jquery\.reel-1\.1\.js
  static_files: reel-1.1.1-min.js
  upload: reel-1\.1\.1-min\.js

- url: /jquery\.reel-1\.1-bundle\.js
  static_files: reel-1.1.1-bundle.js
  upload: reel-1\.1\.1-bundle\.js

- url: /jquery\.reel-1\.1-devel\.js
  static_files: reel-1.1.1.js
  upload: reel-1\.1\.1\.js

# 1.0.x

- url: /jquery\.reel-1\.0\.js
  static_files: reel-1.0.4-min.js
  upload: reel-1\.0\.4-min\.js

- url: /jquery\.reel-1\.0-bundle\.js
  static_files: reel-1.0.4-bundle.js
  upload: reel-1\.0\.4-bundle\.js

- url: /jquery\.reel-1\.0-devel\.js
  static_files: reel-1.0.4.js
  upload: reel-1\.0\.4\.js

# Badges

- url: /jquery\.reel-(\d+)\.gif
  static_files: jquery.reel-\1.gif
  upload: jquery\.reel-\d+\.gif

- url: /favicon\.ico
  static_files: icon.png
  upload: icon\.png

- url: /jquery\.reel\.cursor-drag\.gif
  static_files: jquery.reel.cursor-drag.gif
  upload: jquery\.reel\.cursor-drag\.gif

- url: /jquery\.reel\.cursor-drag-down\.gif
  static_files: jquery.reel.cursor-drag-down.gif
  upload: jquery\.reel\.cursor-drag-down\.gif


# Essentials

- url: /blank\.gif
  static_files: blank.gif
  upload: blank\.gif



- url: /.*
  script: cacheheaders.py
